version: '3.8'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./scripts:/docker-entrypoint-initdb.d

  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mongodb://mongo:27017/incidentsDB
    depends_on:
      - mongo

volumes:
  mongo-data:
